### ISSUE TITLE
Does not work with current Ember

### ISSUE THREAD

**Issue by RobbieTheWagner** [diogomafra/ember-hellgate#1]
There are no views anymore, so this addon does not work. I'm thinking about switching to components and submitting a PR. Is there any work towards a working version yet?

**Comment by diogomafra** [comment]
I think we can register only the template, without the View. I will try to make it work with Ember 2.4.

**Comment by RobbieTheWagner** [comment]
@diogomafra I forked the repo and I was going to try to get it to work, but if you have ideas already, go for it. I just figured rather than using a controller and view, just a component could be used, since components are essentially a controller and view combined.

**Comment by diogomafra** [comment]
@rwwagner90 could you test this [PR](https://github.com/diogomafra/ember-hellgate/pull/2)?

**Comment by RobbieTheWagner** [comment]
@diogomafra I will test it now

**Comment by RobbieTheWagner** [comment]
@diogomafra I tested the PR and it successfully worked in my application. I did notice there is one deprecation though: `The `initialize` method for Application initializer 'ember-hellgate' should take only one argument - `App`, an instance of an `Application`.`

**Comment by RobbieTheWagner** [comment]
I would be glad to fix that deprecation and submit a PR, if you want to go ahead and merge your changes into master.

**Comment by diogomafra** [comment]
Thank you for testing this. Please, submit a PR, I will be glad to merge it. :smile:

**Comment by RobbieTheWagner** [comment]
PR is up. I'd love to tweak this further, especially once routable components are out. Thanks for creating this :)
